export const PLACEHOLDERS = {
  KITAAB_LOGO_ALT: 'kitaab logo',
  SIDEBAR_LI_DASHBOARD: 'Dashboard',
  SIDEBAR_LI_RECORDS: 'Records',
  SIDEBAR_LI_DEEDS: 'Deeds',
  SIDEBAR_LI_NOTIFICATIONS: 'Notifications',
  SIDEBAR_LI_SUPPORT: 'Support',
  SIDEBAR_BTN_LOG_OUT: 'Logout',
  SIDEBAR_LI_HREF_DASHBOARD: '/dashboard',
  SIDEBAR_LI_HREF_RECORDS: '/records',
  SIDEBAR_LI_HREF_DEEDS: '/deeds',
  SIDEBAR_LI_HREF_NOTIFICATIONS: '/notifications',
  SIDEBAR_LI_HREF_SUPPORT: '/support',
  SIDEBAR_NAV_ARIA_LABEL: 'Primary',
  SIDEBAR_BTN_SETTINGS: 'Settings',
  SIDEBAR_BTN_HREF_SETTINGS: '/settings',
  HAMBURGER_BTN_ARIA_LABEL: 'Toggle menu',
  DRAGGABLE_CARD_KEY_TYPE: 'Type',
  DRAGGABLE_CARD_KEY_ADDED: 'Added',
  DRAGGABLE_CARD_KEY_SUB_DEEDS: 'Sub Deeds',
  DRAGGABLE_CARD_KEY_LAST_RECORDED: 'Last Recorded',
  DRAGGABLE_CARD_ADD_SUB_DEED: 'Add Sub Deed',
  DRAGGABLE_CARD_BTN_VIEW_DETAILS: 'View Details',
  PAGE_NAME_DEEDS: 'Deeds',
  CARD_HEADING_DEEDS: 'Deed(s)',
  CARD_HEADING_SCALES: 'Scale(s)',
  MODAL_DELETE_DEED_TITLE: 'Delete Deed',
  MODAL_DELETE_DEED_DESCRIPTION: 'Deleting this deed will permanently delete all associated sub deeds and records. Are you sure you want to continue?',
  NONE: 'None',
  UNDEFINED: 'undefined',
  MODAL_ADD_DEED_TITLE: 'Add Deed',
  MODAL_ADD_SUB_DEED_TITLE: 'Add Sub Deed',
  DEED_NAME_LABEL: 'Name',
  DEED_NAME_PLACEHOLDER: 'e.g. Salah',
  DEED_NAME_REQUIRED_HELPER: 'Name is required',
  DEED_DESCRIPTION_LABEL: 'Description',
  DEED_DESCRIPTION_PLACEHOLDER: 'Briefly describe this deed...',
  ADD_NEW_DEED_BTN: 'Add New Deed',
  MODAL_ADD_SUB_DEED_QUESTION_TITLE: 'Add Sub Deed ?',
  MODAL_ADD_SUB_DEED_QUESTION_DESCRIPTION: 'For example, Salah can include Fajr, Dhuhr, Asr, Maghrib, and Isha as sub deeds.',
  MODAL_ADD_SUB_DEED_ANOTHER_QUESTION_TITLE: 'Add Another Sub Deed ?',
  DRAGGABLE_CARD_VIEW_EDIT_DEED: 'View & Edit',
  USE_FORM_CONTEXT_ERROR: 'useFormContext must be used inside FormProvider',
  MODAL_VIEW_EDIT_DEED_TITLE: 'View & Edit Deed',
  ADD_DEED_CTA: 'Add New Deed',
  DEEDS_REORDER_TOOLTIP: 'Reordering items…',
  DEED_UPDATE_FORM_TOOLTIP: 'Make a change to enable the update button',
  STEPPER_STEP_1: '1',
  STEPPER_STEP_2: '2',
  STEPPER_DEEDS_MANAGEMENT: 'Deed(s) Management',
  STEPPER_SCALES_MANAGEMENT: 'Scale(s) Management',
  STEPPER_NO_DEEDS: 'Nothing to show yet. Add a deed to get started and see it here.',
  STEPPER_BACK: 'Back',
  STEPPER_NEXT: 'Next',
  STEPPER_END: 'End',
  SCALES_COUNT_IT: 'Count It',
  SCALES_COUNT_IT_DEED: 'Tasbeeh',
  SCALES_COUNT_IT_EXAMPLE: '384 times today',
  SCALES_COUNT_IT_H4: 'For deeds you do repeatedly',
  SCALES_COUNT_IT_P: 'Keep a running count of each time you do it.',
  SCALES_YES_NO_B: 'or',
  SCALES_YES_NO_C: 'No',
  SCALES_YES_NO_A: 'Yes',
  SCALES_YES_NO_BTN_A: 'No',
  SCALES_YES_NO_BTN_B: 'Yes',
  SCALES_YES_NO_DEED: 'Sadaqah',
  SCALES_YES_NO_H4: 'For simple daily check-ins',
  SCALES_YES_NO_P: 'Did you do it? Just mark Yes or No.',
  SCALES_CUSTOM_DEED: 'Fajr',
  SCALES_CUSTOM: 'Choose a Scale',
  SCALES_CUSTOM_H4: 'For deeds with different outcomes',
  SCALES_CUSTOM_P: 'Go beyond yes or no. Track how you did it.',
  SCALES_CUSTOM_BTN_C: 'Late',
  SCALES_CUSTOM_BTN_A: 'In Mosque',
  SCALES_CUSTOM_BTN_D: 'Missed',
  SCALES_CUSTOM_BTN_B: 'On Time',
  SCALES_EXAMPLE: 'Example',
  SCALES_SELECT: 'Select',
  SCALES_SELECTED: 'Selected',
  MODAL_VIEW_EDIT_SCALE_TITLE: 'View & Edit Scale',
  MODAL_DELETE_SCALE_TITLE: 'Delete Scale',
  MODAL_DELETE_SCALE_DESCRIPTION: 'Deleting this scale will also delete the associated records permanently. Are you sure you want to continue?',
  MODAL_ADD_SCALE_TITLE: 'Add Scale',
  MODAL_ADD_SCALE_QUESTION_TITLE: 'Add Scale ?',
  MODAL_ADD_SCALE_QUESTION_DESCRIPTION: 'For example, Fajr can include In Mosque, On Time, Late, and Missed as scales.',
  MODAL_ADD_SCALE_ANOTHER_QUESTION_TITLE: 'Add Another Scale ?',
  SCALE_NAME_LABEL: 'Name',
  SCALE_NAME_PLACEHOLDER: 'e.g. Yes',
  SCALE_DESCRIPTION_LABEL: 'Description',
  SCALE_DESCRIPTION_PLACEHOLDER: 'Briefly describe this scale...',
  ADD_SCALE_CTA: 'Add Scale',
  NO_DEEDS_TO_SHOW: 'No deed was created at the following date.',
  RECORD_PREVIOUS_DAYS_REQUIRED: 'Kindly fill in the details for the previous days first so that you can complete today\'s details.',
  FAILED_TO_LOAD_HIGHCHARTS: 'Failed to load Highcharts:'
};