export const PLACEHOLDERS = {
  KITAAB_LOGO_ALT: 'kitaab logo',
  SIDEBAR_LI_DASHBOARD: 'Dashboard',
  SIDEBAR_LI_RECORDS: 'Records',
  SIDEBAR_LI_DEEDS: 'Deeds',
  SIDEBAR_LI_NOTIFICATIONS: 'Notifications',
  SIDEBAR_LI_SUPPORT: 'Support',
  SIDEBAR_BTN_LOG_OUT: 'Logout',
  SIDEBAR_LI_HREF_DASHBOARD: '/dashboard',
  SIDEBAR_LI_HREF_RECORDS: '/records',
  SIDEBAR_LI_HREF_DEEDS: '/deeds',
  SIDEBAR_LI_HREF_NOTIFICATIONS: '/notifications',
  SIDEBAR_LI_HREF_SUPPORT: '/support',
  SIDEBAR_NAV_ARIA_LABEL: 'Primary',
  SIDEBAR_BTN_SETTINGS: 'Settings',
  SIDEBAR_BTN_HREF_SETTINGS: '/settings',
  HAMBURGER_BTN_ARIA_LABEL: 'Toggle menu',
  DRAGGABLE_CARD_KEY_TYPE: 'Type',
  DRAGGABLE_CARD_KEY_ADDED: 'Added',
  DRAGGABLE_CARD_KEY_SUB_DEEDS: 'Sub Deeds',
  DRAGGABLE_CARD_KEY_LAST_RECORDED: 'Last Recorded',
  DRAGGABLE_CARD_ADD_SUB_DEED: 'Add Sub Deed',
  DRAGGABLE_CARD_BTN_VIEW_DETAILS: 'View Details',
  PAGE_NAME_DEEDS: 'Deeds',
  MODAL_DELETE_DEED_TITLE: 'Delete Deed',
  MODAL_DELETE_DEED_DESCRIPTION: 'Deleting this deed will permanently delete all associated sub deeds and records. Are you sure you want to continue?',
  NONE: 'None',
  UNDEFINED: 'undefined',
  MODAL_ADD_DEED_TITLE: 'Add Deed',
  MODAL_ADD_SUB_DEED_TITLE: 'Add Sub Deed',
  DEED_NAME_LABEL: 'Name',
  DEED_NAME_PLACEHOLDER: 'e.g. Salah',
  DEED_NAME_REQUIRED_HELPER: 'Name is required',
  DEED_DESCRIPTION_LABEL: 'Description',
  DEED_DESCRIPTION_PLACEHOLDER: 'Briefly describe this deed...',
  ADD_NEW_DEED_BTN: 'Add New Deed',
  MODAL_ADD_SUB_DEED_QUESTION_TITLE: 'Add Sub Deed ?',
  MODAL_ADD_SUB_DEED_QUESTION_DESCRIPTION: 'For example, Salah can include Fajr, Dhuhr, Asr, Maghrib, and Isha as sub deeds.',
  MODAL_ADD_SUB_DEED_ANOTHER_QUESTION_TITLE: 'Add Another Sub Deed ?',
  DRAGGABLE_CARD_VIEW_EDIT_DEED: 'View & Edit'
};