import './globals.css';
import type { Metadata } from 'next';
import styles from './layout.module.css';
import StoreProvider from '@/store/Provider';
import { ChildrenProps } from '@/store/slices/interface';
import Header from '@/components/composite/header/Header';
import Sidebar from '@/components/composite/sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'Kitaab',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<ChildrenProps>) {
  return (
    <html lang='en'>
      <body>
        <StoreProvider>
          <Sidebar />
          <div className={styles.container}>
            <Header />
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
};