import './globals.css';
import type { Metadata } from 'next';
import StoreProvider from '@/store/Provider';
import Sidebar from '@/components/composite/sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'Kitaab',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang='en'>
      <body>
        <StoreProvider>
          <Sidebar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
};